version: "3"

services:
  nginx-reverse-proxy:
    image: nginx:stable-alpine
    container_name: nginx-reverse-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
    networks:
      - my-network
networks:
  my-network:
    name: my-network
